/* Original fan-sequel scenario. Fessenden's defeat remains the end of his story. */
window.EDEN_CAMPAIGN = [
 {name:'THE DROWNED HARBOR',area:'01 / THE STOLEN WARNING',theme:'harbor',length:4200,boss:'WARDEN ROOK',kind:'warden',sky:['#354e58','#c3936d'],road:['#505b46','#323e37'],accent:'#efb36d',brief:'Jack and Hannah made it out of Fessenden’s collapsing laboratory. The Cadillac brought all four friends home. Three months later, a flood warning reaches Jack’s garage — moments before armed dock guards steal its transmitter. Someone wants the coast to stay asleep.',dialog:'HANNAH: Those tide readings are real. We have one night.\nMUSTAPHA: Then somebody picked the wrong night to steal our radio.',end:'Rook’s orders name Marshal Sable, the coast’s new water commissioner. He has seized the Crown flood barrier and the evacuation maps. Jack spots the stolen transmitter on a tanker heading inland. The Cadillac is ready.'},
 {name:'THE GREEN HIGHWAY',area:'02 / CHASE THE SIGNAL',theme:'highway',drive:true,length:4300,boss:'IRON CONVOY',kind:'truck',sky:['#395947','#afad68'],road:['#52544d','#353a34'],accent:'#d2df7b',brief:'Sable’s tanker is carrying the transmitter and a stolen gate governor. Without that governor, opening the Crown barrier will send the entire reservoir into the settlements. Catch the tanker before the expressway ends.',dialog:'MESS: How much water can one man steal?\nJACK: Enough to make everyone else pay for it.',end:'The escort breaks. Hannah recovers the transmitter and sends the first evacuation warning. The governor is intact, but Sable has blocked the safe road with sonic beacons that drive migrating dinosaurs toward the refugees. The gang turns into the basin.'},
 {name:'THE VERDANT BASIN',area:'03 / OPEN THE PASSAGE',theme:'jungle',length:4400,boss:'THORNMAW',kind:'raptor',sky:['#203b35','#6e9270'],road:['#4c5b32','#293c29'],accent:'#accb6d',brief:'The last dry passage runs through a nesting ground. Thornmaw is defending its young from Sable’s sonic lures. Fight through the hired hunters, silence the nest beacon and give the herd a way out.',dialog:'HANNAH: It isn’t hunting us. We’re between it and its nest.\nMESS: Then we move the men who put us here.',end:'The beacon breaks and Thornmaw withdraws with its young. Families and dinosaurs cross the same dry ridge. Hannah names the refuge beyond it Last Eden. The recovered governor needs a drive coupling; Sable’s foundry holds the only replacement.'},
 {name:'THE ASHEN FOUNDRY',area:'04 / BORROWED FIRE',theme:'foundry',length:4450,boss:'FOREMAN CINDER',kind:'cinder',sky:['#2f3238','#83533c'],road:['#53504b','#313632'],accent:'#eea05c',brief:'Cinder is melting down the coast’s pumps to build Sable’s armored floodgate rig. Reach the machine shop and salvage its last governor coupling before the furnace consumes it.',dialog:'CINDER: Water belongs to whoever can hold the gate.\nJACK: Funny. I was about to take it off your hands.',end:'Mess pulls the coupling from Cinder’s wrecked press. Jack repairs the governor. Its old service map reveals a pressure tunnel into Crown — but the tide archive must unlock it. Sable is already flooding the lower road.'},
 {name:'THE TIDE ARCHIVE',area:'05 / A VOICE ON THE RADIO',theme:'lab',length:4400,boss:'SIGNAL CAPTAIN ECHO',kind:'echo',sky:['#152c36','#35595e'],road:['#4e6664','#283e43'],accent:'#7bd6c9',brief:'The pumping station’s archive holds the pressure-tunnel controls. Captain Echo jams the evacuation channel and broadcasts false directions. Retake the relay before the families on the ridge follow his signal into the rising water.',dialog:'ECHO: Turn back. The ridge is closed.\nHANNAH: This is Hannah Dundee. Stay on the high road. We’re coming.',end:'Echo’s jammer goes silent. The settlements hear Hannah’s real warning and open their shelters. Jack unlocks the service tunnel. Sable offers them safe passage if they abandon everyone else. Nobody answers. The Cadillac enters the tunnel.'},
 {name:'THE CROWN BARRIER',area:'06 / LAST EDEN',theme:'eden',length:4650,boss:'MARSHAL SABLE',kind:'sable',sky:['#132d29','#507659'],road:['#46634c','#263b31'],accent:'#d5ec69',brief:'At sunrise Sable will open the reservoir into the lowlands, forcing every survivor to buy water and shelter from him. Fit the repaired governor, defeat Sable and stop his Crown Engine before it tears the floodgate free.',dialog:'SABLE: They’ll thank the man who decides who survives.\nMUSTAPHA: Let’s take that decision away from you.',end:'The Crown Engine stalls. Jack fits the governor while Mess holds the manual release. Hannah radios the shelters; Mustapha opens the spillway. Water returns to the old riverbed instead of the settlements. Last Eden survives the dawn.'}
];
