/* Cadillacs & Dinosaurs II: Last Eden — original local fan-game engine. */
(() => {
'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),overlay=document.querySelector('#overlay');
const A=window.ARCADE_ASSETS,sheet=new Image();sheet.src=A.sheet;
const W=768,H=432,GROUND=254,FLOOR=407;
const HEROES=[
 {id:'mustapha',name:'MUSTAPHA',nickname:'MOSTAFA',tag:'THE FLYING KICK',hp:120,speed:167,power:21,color:'#d5ec69',special:'Cyclone kick'},
 {id:'jack',name:'JACK TENREC',nickname:'',tag:'THE ALL-ROUNDER',hp:140,speed:145,power:23,color:'#7dc4de',special:'Rising uppercut'},
 {id:'hannah',name:'HANNAH DUNDEE',nickname:'',tag:'THE SWIFT STRIKER',hp:110,speed:180,power:19,color:'#efaa77',special:'Spinning sweep'},
 {id:'mess',name:'MESS O\'BRADOVICH',nickname:'',tag:'THE HEAVY HITTER',hp:170,speed:122,power:29,color:'#b5cc85',special:'Seismic smash'}
];
const LEVELS=[
 {name:'THE DROWNED HARBOR',area:'01 / CITY OF THE LOST',theme:'harbor',length:2700,boss:'WARDEN ROOK',kind:'warden',sky:['#354e58','#c3936d'],road:['#505b46','#323e37'],accent:'#efb36d',brief:'Six months after Fessenden fell, a black convoy arrives at the harbor. Its cargo: living dinosaurs. Its destination: a place marked EDEN.',dialog:'JACK: Those cages are headed inland.\nMUSTAPHA: Then we follow the tire tracks.',end:'Rook drops a convoy manifest. Someone called Dr. Mara Voss is harvesting the last unaltered dinosaur bloodlines. A highway leads toward her hidden laboratory.'},
 {name:'THE GREEN HIGHWAY',area:'02 / CONVOY PURSUIT',theme:'highway',drive:true,length:2850,boss:'IRON CONVOY',kind:'truck',sky:['#395947','#afad68'],road:['#52544d','#353a34'],accent:'#d2df7b',brief:'Jack brings the Cadillac out of retirement. The convoy is racing along the abandoned expressway. Cut off its armored escort before it reaches the jungle.',dialog:'JACK: Everybody buckle up.\nHANNAH: You did fix the brakes, right?',end:'The convoy carries a wounded young dinosaur, not a weapon. Hannah frees it. A locator on its cage points to the Verdant Basin. The old world is waking up.'},
 {name:'THE VERDANT BASIN',area:'03 / INTO THE WILD',theme:'jungle',length:2900,boss:'THORNMAW',kind:'raptor',sky:['#203b35','#6e9270'],road:['#4c5b32','#293c29'],accent:'#accb6d',brief:'The jungle has swallowed the suburbs. Voss has turned its hunting grounds into a testing field. Her spores drive the dinosaurs into a frenzy.',dialog:'HANNAH: That growth is changing them.\nMESS: We find the source. We break it.',end:'Thornmaw falls. The surviving animals flee as their control collars go dark. A pipeline carries the same glowing spores into the old industrial district.'},
 {name:'THE ASHEN FOUNDRY',area:'04 / FIRE UNDER THE CITY',theme:'foundry',length:2950,boss:'FOREMAN CINDER',kind:'cinder',sky:['#2f3238','#83533c'],road:['#53504b','#313632'],accent:'#eea05c',brief:'Inside the foundry, stolen engines power a serum refinery. Voss is building an army, and a former poacher now guards her furnace gates.',dialog:'MUSTAPHA: This place smells like trouble.\nJACK: Trouble with a very large power bill.',end:'Cinder\'s refinery collapses. Behind the furnace is an elevator to a pre-cataclysm research station. Its logs call Voss\'s project the Pale Regent.'},
 {name:'THE MIRROR LAB',area:'05 / PROJECT REGENT',theme:'lab',length:2800,boss:'SENTINEL ECHO',kind:'echo',sky:['#152c36','#35595e'],road:['#4e6664','#283e43'],accent:'#7bd6c9',brief:'The lab grows creatures that should never exist. Sentinel Echo learns from every intruder. Destroy its chambers before it can finish mapping the heroes.',dialog:'HANNAH: She isn\'t saving the species.\nJACK: She\'s replacing them.',end:'Echo shatters. Voss broadcasts from the seed vault below: "The world had its chance. Eden will belong to a stronger species." The final descent begins.'},
 {name:'THE LAST EDEN',area:'06 / THE SEED VAULT',theme:'eden',length:3050,boss:'DR. MARA VOSS',kind:'regent',sky:['#132d29','#507659'],road:['#46634c','#263b31'],accent:'#d5ec69',brief:'An ancient vault protects the seeds of a living world. Voss has wired it to her mutation reactor. Shut it down before the last natural refuge becomes a breeding ground.',dialog:'VOSS: I offered this world a future.\nMUSTAPHA: A future needs a choice.',end:'The reactor goes silent. Daylight reaches Eden for the first time in centuries. Voss\'s army loses its control signal, and the dinosaurs return to the wild.'}
];
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),approach=(x,y,s)=>x<y?Math.min(x+s,y):Math.max(x-s,y);
const keys=new Set(),pressed=new Set(),touchKeys=new Set(),padKeys=new Set();
let state='menu',selected=0,difficulty='story',levelIndex=0,level=LEVELS[0],time=0,last=0,camera=0,shake=0,flash=0,hitstop=0;
let player,enemies=[],objects=[],drops=[],particles=[],bullets=[],zones=[],floating=[],wave=0,lock=null,bossSpawned=false,cleared=false,stageTimer=0;
let score=0,lives=3,combo=0,comboTimer=0,bestCombo=0,kills=0,runTime=0,toast='',toastTime=0,started=false;
let save={unlocked:0,checkpoint:null,best:0},settings={music:true,sfx:true},musicStep=0,musicTimer=0;
try{save={...save,...JSON.parse(localStorage.getItem('last-eden-save')||'{}')};settings={...settings,...JSON.parse(localStorage.getItem('last-eden-settings')||'{}')};}catch{}
save.unlocked=clamp(Number(save.unlocked)||0,0,5);
function persist(){try{localStorage.setItem('last-eden-save',JSON.stringify(save));localStorage.setItem('last-eden-settings',JSON.stringify(settings));}catch{}}
function checkpoint(){save.checkpoint={level:levelIndex,hero:selected,difficulty,score,lives};persist();}
let audio;
function unlockAudio(){if(!audio){const AC=window.AudioContext||window.webkitAudioContext;if(AC)audio=new AC();}if(audio?.state==='suspended')audio.resume();}
function tone(freq,dur=.12,type='square',vol=.04,end){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(20,end),audio.currentTime+dur);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur);}
function sfx(name){if(!settings.sfx)return;unlockAudio();if(name==='hit'){tone(130,.09,'sawtooth',.09,35);tone(630,.045,'square',.025,60);}if(name==='jump')tone(190,.15,'triangle',.06,550);if(name==='gun')tone(900,.09,'sawtooth',.065,50);if(name==='pickup'){tone(440,.1,'square',.04);setTimeout(()=>tone(660,.1,'square',.04),70);}if(name==='special'){tone(90,.35,'sawtooth',.07,600);tone(440,.25,'triangle',.04,100);}if(name==='hurt')tone(180,.2,'sawtooth',.06,40);if(name==='clear'){[392,494,587,784].forEach((f,i)=>setTimeout(()=>tone(f,.3,'triangle',.05),i*100));}}
function music(dt){if(!settings.music||!audio||state==='paused')return;musicTimer-=dt;if(musicTimer>0)return;musicTimer=.19;const roots=[110,98,123.47,82.41,110,98,73.42,82.41],r=roots[(musicStep>>4)%8]*(levelIndex===5?.89:1);tone(r*(musicStep%4===2?2:1),.16,'triangle',.025);if(musicStep%4===0)tone(65,.08,'sine',.035,25);if(musicStep%2===0)tone(3000,.035,'square',.004,1800);if(musicStep%8===5)tone(r*4,.26,'triangle',.018);musicStep++;}
function bindButton(id,fn){document.getElementById(id)?.addEventListener('click',()=>{unlockAudio();fn();});}
function panel(html){overlay.innerHTML=html;document.querySelector('#pause').style.display=state==='play'?'block':'none';}
function menu(){state='menu';lock=null;keys.clear();panel(`<section class="panel title-panel"><p class="eyebrow">THE OLD WORLD. A NEW FIGHT.</p><h1>CADILLACS &<br>DINOSAURS <span>II</span></h1><div class="subtitle">LAST EDEN</div><p class="deck">Four familiar heroes. Six new chapters.<br>One last chance for a world worth saving.</p><div class="menu-buttons"><button class="primary" id="newgame">START ADVENTURE →</button>${save.checkpoint?'<button class="secondary" id="continue">CONTINUE</button>':''}<button class="secondary" id="chapters">CHAPTERS</button><button class="secondary" id="guide">HOW TO PLAY</button></div><p class="title-note">A FAN-MADE SEQUEL · MADE FOR MOSTAFA</p></section>`);bindButton('newgame',()=>characterSelect());bindButton('continue',()=>{const s=save.checkpoint;selected=clamp(s.hero,0,3);difficulty=s.difficulty==='arcade'?'arcade':'story';score=s.score||0;lives=s.lives||3;startStage(clamp(s.level,0,5));});bindButton('chapters',chapters);bindButton('guide',()=>guide(menu));}
function characterSelect(startAt=0){state='select';panel(`<section class="panel character-panel"><p class="eyebrow">CHOOSE YOUR HERO</p><h2>THE GANG IS BACK.</h2><div class="hero-grid">${HEROES.map((h,i)=>`<button class="hero-card ${i===selected?'selected':''}" data-hero="${i}"><div class="hero-art"><canvas width="100" height="110" id="portrait-${i}" aria-label="${h.name}"></canvas></div><div class="hero-name">${h.name}</div><div class="hero-tag">${h.tag}</div><div class="hero-stats"><span>POWER ${Math.round(h.power/6)}</span><span>SPEED ${Math.round(h.speed/36)}</span></div></button>`).join('')}</div><div class="select-row"><div class="difficulty"><button id="story-mode" class="${difficulty==='story'?'selected':''}">STORY</button><button id="arcade-mode" class="${difficulty==='arcade'?'selected':''}">ARCADE</button></div><span class="hint">${difficulty==='story'?'More health · forgiving fights':'Faster enemies · harder bosses'}</span><button id="begin" class="primary">LET'S GO →</button></div><div class="menu-buttons"><button id="back" class="secondary">← BACK</button></div></section>`);
 document.querySelectorAll('[data-hero]').forEach(b=>b.onclick=()=>{selected=+b.dataset.hero;characterSelect(startAt);sfx('pickup');});bindButton('story-mode',()=>{difficulty='story';characterSelect(startAt);});bindButton('arcade-mode',()=>{difficulty='arcade';characterSelect(startAt);});bindButton('begin',()=>{score=0;lives=3;kills=0;bestCombo=0;runTime=0;startStage(startAt);});bindButton('back',menu);HEROES.forEach((h,i)=>{const c=document.querySelector('#portrait-'+i),g=c.getContext('2d');g.imageSmoothingEnabled=false;drawFrame(g,A[h.id].frames[0],50,108,1.25,1);});}
function chapters(){state='chapters';panel(`<section class="panel small-panel"><p class="eyebrow">THE ROAD TO EDEN</p><h2>SIX CHAPTERS. ONE WORLD.</h2><p>Clear a chapter to unlock it here. Your campaign saves at the start of each chapter.</p><div class="level-grid">${LEVELS.map((l,i)=>`<button data-level="${i}" ${i>save.unlocked?'disabled':''}><span>CHAPTER 0${i+1} ${i>save.unlocked?'· LOCKED':''}</span>${l.name}</button>`).join('')}</div><div class="menu-buttons"><button id="back" class="secondary">← MAIN MENU</button></div></section>`);document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>characterSelect(+b.dataset.level));bindButton('back',menu);}
function guide(back){state='guide';panel(`<section class="panel small-panel"><p class="eyebrow">ARCADE FIELD GUIDE</p><h2>GET BACK IN THE FIGHT.</h2><div class="controls-list"><strong>WASD / ↑↓←→</strong><span>Move along the street and between lanes.</span><strong>J / Z</strong><span>Hold to chain punches. Attack in the air for a flying kick.</span><strong>K / X</strong><span>Jump. Dodge shockwaves and low attacks.</span><strong>L / C</strong><span>Special move. Costs a little health. In the car: ram.</span><strong>E / V</strong><span>Pick up a nearby weapon or item. Throw your weapon if holding one.</span><strong>SHIFT</strong><span>Run. Attack while running for a dash strike.</span><strong>ESC / P</strong><span>Pause. Gamepad: stick / D-pad, X hit, A jump, Y special, B pick.</span></div><p>Break barrels for food and weapons. Walk to the right after clearing an encounter. Red attack markers mean dodge or jump. Highway controls: steer, J fire, K boost, L ram.</p><div class="menu-buttons"><button id="back" class="primary">GOT IT →</button></div></section>`);bindButton('back',back);}
function startStage(i,skipBrief=false){levelIndex=i;level=LEVELS[i];const hero=HEROES[selected];player={x:130,y:352,z:0,vz:0,dir:1,hp:hero.hp*(difficulty==='story'?1.4:1),maxhp:hero.hp*(difficulty==='story'?1.4:1),hurt:0,inv:1.5,attack:0,attackTotal:.38,special:0,specialCd:0,comboStep:0,weapon:null,ammo:0,move:false,run:false,anim:0,boost:0,boostCd:0};
 enemies=[];objects=[];drops=[];particles=[];bullets=[];zones=[];floating=[];wave=0;lock=null;camera=0;bossSpawned=false;cleared=false;stageTimer=0;combo=0;comboTimer=0;shake=0;flash=0;checkpoint();
 if(!level.drive){for(let j=0;j<9;j++)objects.push({x:340+j*280,y:rand(310,385),hp:26,type:j%3===0?'crate':'barrel',content:j%3===0?'gun':j%3===1?'food':'knife'});drops.push({x:260,y:375,type:'food',life:999});}
 started=true;toast=level.drive?'STEER ↑↓ · J FIRE · K BOOST · L RAM':'MOVE → · J ATTACK · K JUMP · E PICK UP';toastTime=7;
 if(skipBrief){state='play';panel('');canvas.focus();return;}
 state='brief';panel(`<section class="panel small-panel"><p class="eyebrow">CHAPTER 0${i+1} · ${level.area.split('/')[1].trim()}</p><h2>${level.name}</h2><p>${level.brief}</p><p style="color:var(--acid);white-space:pre-line">${level.dialog}</p><div class="menu-buttons"><button id="enter-stage" class="primary">${level.drive?'START YOUR ENGINE':'ENTER THE CHAPTER'} →</button></div></section>`);bindButton('enter-stage',()=>{state='play';panel('');keys.clear();pressed.clear();canvas.focus();});}
function pause(){if(state==='play'){state='paused';keys.clear();pressed.clear();panel(`<section class="panel small-panel"><p class="eyebrow">TAKE A BREATHER</p><h2>PAUSED.</h2><p>Chapter 0${levelIndex+1} · ${level.name}<br>Your checkpoint is saved at the start of this chapter.</p><div class="menu-buttons"><button id="resume" class="primary">RESUME →</button><button id="controls" class="secondary">CONTROLS</button><button id="restart" class="secondary">RESTART CHAPTER</button><button id="quit" class="secondary">MAIN MENU</button></div></section>`);bindButton('resume',resume);bindButton('controls',()=>guide(()=>{state='play';pause();}));bindButton('restart',()=>startStage(levelIndex));bindButton('quit',()=>{checkpoint();menu();});}else if(state==='paused')resume();}
function resume(){state='play';panel('');keys.clear();pressed.clear();canvas.focus();}
function gameover(){state='gameover';save.best=Math.max(save.best,score);persist();panel(`<section class="panel small-panel"><p class="eyebrow">THE FIGHT ISN'T OVER</p><h2>CONTINUE?</h2><p>The gang regroups at the start of this chapter. No coins needed.<br>Score ${score.toString().padStart(6,'0')} · Best combo ${bestCombo}</p><div class="menu-buttons"><button id="retry" class="primary">TRY AGAIN →</button><button id="quit" class="secondary">MAIN MENU</button></div></section>`);bindButton('retry',()=>{lives=3;startStage(levelIndex);});bindButton('quit',menu);}
function stageClear(){if(cleared)return;cleared=true;state='clear';score+=2500+Math.floor(player.hp*10);save.unlocked=Math.max(save.unlocked,Math.min(5,levelIndex+1));save.best=Math.max(save.best,score);sfx('clear');save.checkpoint=levelIndex<5?{level:levelIndex+1,hero:selected,difficulty,score,lives}:null;persist();panel(`<section class="panel small-panel"><p class="eyebrow">CHAPTER 0${levelIndex+1} COMPLETE</p><h2>${levelIndex===5?'EDEN IS FREE.':'KEEP THE ENGINE RUNNING.'}</h2><p>${level.end}</p><p style="color:var(--acid)">SCORE ${score.toString().padStart(6,'0')} · BEST COMBO ${bestCombo}</p><div class="menu-buttons"><button id="next" class="primary">${levelIndex===5?'SEE THE ENDING':'NEXT CHAPTER'} →</button></div></section>`);bindButton('next',()=>levelIndex<5?startStage(levelIndex+1):ending());}
function ending(){state='ending';save.checkpoint=null;persist();panel(`<section class="panel small-panel"><p class="eyebrow">LAST EDEN · THE END</p><h2>A WORLD WORTH SAVING.</h2><p>Hannah opens the vault. Jack disconnects the reactor. Mess lifts the fallen gate, and Mustapha leads the rescued animals into the sunrise.</p><p>The Cadillac rolls home carrying four tired heroes, a box of seeds, and one very stubborn baby dinosaur.</p><p style="color:var(--acid)">MUSTAPHA: Same time next adventure?<br>JACK: Only if you're buying the fuel.</p><p>${kills} enemies defeated · ${Math.floor(runTime/60)} minutes · score ${score}<br>All six chapters are now available.</p><div class="menu-buttons"><button id="chapters" class="primary">PLAY A CHAPTER →</button><button id="credits" class="secondary">CREDITS</button><button id="quit" class="secondary">MAIN MENU</button></div></section>`);bindButton('chapters',chapters);bindButton('credits',credits);bindButton('quit',menu);}
function credits(){state='credits';panel(`<section class="panel small-panel"><p class="eyebrow">THANKS FOR PLAYING</p><h2>FOR THE OLD ARCADE DAYS.</h2><p>An unofficial fan sequel created for Mostafa's next adventure. Original character graphics were recovered from the arcade ROM files supplied by the user.</p><p>New story, levels, environments, combat engine, boss behaviors and synthesized soundtrack created for this game. Original Cadillacs and Dinosaurs arcade game and artwork: Capcom. Characters and setting derive from Xenozoic Tales by Mark Schultz.</p><div class="menu-buttons"><button id="quit" class="primary">MAIN MENU →</button></div></section>`);bindButton('quit',menu);}
function spawnEnemy(x,y,type='raider',boss=false){const hp=boss?[210,270,280,330,370,380][levelIndex]:(type==='brute'?76:type==='gunner'?38:type==='raptor'?55:46);const e={id:Math.random(),x,y,z:0,dir:-1,hp:hp*(difficulty==='story'?.8:1.25),maxhp:hp*(difficulty==='story'?.8:1.25),type,boss,phase:1,state:'walk',timer:rand(.5,2),hurt:0,inv:0,anim:rand(0,1),dead:0,attack:0,palette:type==='gunner'?'14':'13',hue:type==='brute'?80:type==='gunner'?15:0};enemies.push(e);return e;}
function spawnWave(n){wave=n;lock={left:Math.max(0,player.x-155),right:Math.min(level.length+240,player.x+570)};const count=difficulty==='story'?3+Math.floor(levelIndex/2):4+Math.floor(levelIndex/2);for(let j=0;j<count;j++){const type=level.drive?'biker':levelIndex>=2&&j===count-1?'raptor':j%3===1?'gunner':j%4===3?'brute':'raider';spawnEnemy(player.x+330+j*46,rand(292,386),type);}toast=level.drive?'CONVOY ESCORT · CLEAR THE ROAD':'AMBUSH · CLEAR THE AREA';toastTime=2.2;}
function spawnBoss(){bossSpawned=true;lock={left:level.length-520,right:level.length+100};const b=spawnEnemy(level.length-100,343,level.kind,true);b.timer=2;toast=level.boss;toastTime=3.5;sfx('special');}
function popup(x,y,text,color='#e9ecd1'){floating.push({x,y,text,color,life:1.15});}
function burst(x,y,color,n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-120,120),vy:rand(-140,60),life:rand(.18,.55),size:rand(2,5),color});}
function damageEnemy(e,amount,knock=0){if(e.dead||e.inv>0)return; e.hp-=amount;e.hurt=e.boss?.08:.21;e.inv=.12;e.x+=knock*(e.boss?.3:1);if(lock)e.x=clamp(e.x,lock.left+20,lock.right-35);if(!e.boss){e.state='hurt';e.timer=.35;}combo++;comboTimer=2.2;bestCombo=Math.max(bestCombo,combo);score+=Math.floor(amount*3);burst(e.x,e.y-48,'#ffe2a1',10);sfx('hit');hitstop=.035;shake=3;
 if(e.hp<=0){if(e.boss&&e.type==='regent'&&e.phase===1){e.phase=2;e.hp=e.maxhp=650*(difficulty==='story'?.8:1.2);e.type='regent';e.state='transform';e.timer=2.7;e.inv=2.7;flash=.75;shake=12;toast='THE PALE REGENT · FINAL FORM';toastTime=4;burst(e.x,e.y-65,'#d5ec69',55);sfx('special');return;} e.dead=.9;e.state='dead';score+=e.boss?1500:250;kills++;burst(e.x,e.y-35,e.boss?'#d5ec69':'#a6ba76',16);if(!e.boss&&Math.random()<.24)drops.push({x:e.x,y:e.y,type:Math.random()<.55?'food':'gun',life:32});}
}
function damagePlayer(amount,fromX,ignoreAir=false){if(player.inv>0||(!ignoreAir&&player.z>28)||player.special>0||player.boost>0)return;player.hp-=amount*(difficulty==='story'?.65:1);player.hurt=.35;player.inv=.95;player.x+=fromX<player.x?15:-15;player.attack=0;combo=0;comboTimer=0;shake=6;flash=.07;sfx('hurt');burst(player.x,player.y-48,'#eea575',8);if(player.hp<=0){lives--;if(lives>0){player.hp=player.maxhp;player.inv=3;player.weapon=null;player.ammo=0;popup(player.x,player.y-95,'BACK IN THE FIGHT','#d5ec69');toast=`${lives} LIVES REMAINING`;toastTime=3;checkpoint();}else gameover();}}
function shoot(x,y,dir,friendly=true,damage=18,speed=620){bullets.push({x,y,z:level.drive?28:48,vx:dir*speed,vy:0,friendly,damage,life:1.5,color:friendly?'#fff4af':'#ef8f68'});}
function attack(){if(player.hurt>0||player.attack>0||player.special>0)return;const h=HEROES[selected];player.attackTotal=level.drive?.17:player.z>8?.38:player.run?.43:.32;player.attack=player.attackTotal;player.comboStep=(player.comboStep+1)%3;sfx(level.drive||player.weapon==='gun'?'gun':'hit');
 if(level.drive||player.weapon==='gun'){shoot(player.x+(level.drive?78:25)*player.dir,player.y,player.dir,true,level.drive?22:32);if(!level.drive&&--player.ammo<=0){player.weapon=null;toast='OUT OF AMMO';toastTime=1.4;}return;}
 if(player.weapon==='bomb'){zones.push({x:player.x+player.dir*145,y:player.y,r:100,t:.55,total:.55,friendly:true,damage:110,air:false});player.weapon=null;player.ammo=0;return;}
 const range=player.weapon==='knife'?94:player.z>8?95:player.run?102:76;const power=h.power*(player.z>8?1.35:player.run?1.4:1)*(player.weapon==='knife'?1.6:1)*(player.comboStep===2?1.15:1);
 for(const e of enemies)if(!e.dead&&Math.abs(e.y-player.y)<38&&Math.abs(e.x-player.x)<range&&Math.sign(e.x-player.x)===player.dir)damageEnemy(e,power,player.dir*(player.comboStep===2?18:6));
 for(const o of objects)if(o.hp>0&&Math.abs(o.y-player.y)<35&&Math.abs(o.x-player.x)<85){o.hp-=power;burst(o.x,o.y-35,'#c3925d',8);if(o.hp<=0){drops.push({x:o.x,y:o.y,type:o.content,life:60});score+=100;sfx('pickup');}}
 if(player.weapon==='knife'&&--player.ammo<=0)player.weapon=null;
}
function jump(){if(player.z>0||player.hurt>0)return;if(level.drive){if(player.boostCd<=0){player.boost=1.15;player.boostCd=3;player.inv=1.2;sfx('jump');}return;}player.vz=355;player.z=.1;sfx('jump');}
function special(){if(player.specialCd>0||player.hurt>0)return;if(!level.drive&&player.hp<12){toast='SPECIAL NEEDS 12 HEALTH';toastTime=1.4;return;}player.special=.65;player.specialCd=2.3;player.inv=.8;if(!level.drive)player.hp=Math.max(1,player.hp-8);sfx('special');shake=7;for(const e of enemies)if(!e.dead&&Math.hypot((e.x-player.x)*.8,e.y-player.y)<150)damageEnemy(e,HEROES[selected].power*2.4,Math.sign(e.x-player.x)*35);for(const o of objects)if(o.hp>0&&Math.abs(o.x-player.x)<125&&Math.abs(o.y-player.y)<75){o.hp=0;drops.push({x:o.x,y:o.y,type:o.content,life:60});}burst(player.x,player.y-40,HEROES[selected].color,24);}
function pickup(){let nearest=null,dist=65;for(const d of drops){const dd=Math.hypot(d.x-player.x,d.y-player.y);if(dd<dist){dist=dd;nearest=d;}}if(nearest){if(nearest.type==='food'){player.hp=Math.min(player.maxhp,player.hp+45);popup(player.x,player.y-96,'+45 HEALTH','#d5ec69');}else{player.weapon=nearest.type;player.ammo=nearest.type==='gun'?24:nearest.type==='knife'?16:1;toast=`${nearest.type.toUpperCase()} EQUIPPED · J ATTACK`;toastTime=2;}drops.splice(drops.indexOf(nearest),1);sfx('pickup');score+=75;return;}if(player.weapon){shoot(player.x,player.y,player.dir,true,50,400);player.weapon=null;player.ammo=0;sfx('gun');}}
function bossMove(e){e.state='windup';e.timer=e.phase===2?.7:1; e.action=e.type==='truck'?'volley':e.type==='raptor'?'acid':e.type==='cinder'?'charge':e.type==='echo'?(Math.random()<.4?'summon':'pulse'):e.type==='regent'?(e.phase===2?'slam':'volley'):'punch';if(e.action==='charge'){e.targetY=player.y;e.dir=Math.sign(player.x-e.x)||-1;}if(['slam','pulse','acid'].includes(e.action)){zones.push({x:player.x,y:player.y,r:e.action==='slam'?110:75,t:e.timer,total:e.timer,friendly:false,damage:e.phase===2?28:18,air:e.action!=='acid'});} }
function executeBoss(e){if(e.action==='volley'){for(let j=-1;j<=1;j++){const dy=j*35;const dir=Math.sign(player.x-e.x)||-1;shoot(e.x+dir*40,e.y+dy,dir,false,18,310);}}if(e.action==='charge'){e.state='charge';e.timer=.72;e.vx=e.dir*480;return;}if(e.action==='punch'&&Math.abs(player.x-e.x)<110&&Math.abs(player.y-e.y)<45)damagePlayer(24,e.x);if(e.action==='summon'&&enemies.filter(v=>!v.dead&&!v.boss).length<4){spawnEnemy(e.x-95,e.y+30,'gunner');spawnEnemy(e.x+80,e.y-35,'raider');toast='ECHO IS CALLING REINFORCEMENTS';toastTime=2;}if(e.action==='slam'||e.action==='pulse'){shake=10;burst(e.x,e.y-50,'#d5ec69',18);}e.state='walk';e.timer=e.phase===2?.9:1.7;}
function updateEnemy(e,dt){e.anim+=dt;e.hurt=Math.max(0,e.hurt-dt);e.inv=Math.max(0,e.inv-dt);if(e.dead){e.dead-=dt;if(e.dead<=0)e.remove=true;return;}e.timer-=dt;if(e.state==='transform') {if(e.timer<=0)e.state='walk';return;}if(e.hurt>0)return;if(e.state==='hurt'){if(e.timer<=0){e.state='walk';e.timer=.8;}return;}if(e.state==='windup'){if(e.timer<=0){if(e.boss)executeBoss(e);else{if(e.type==='gunner'||e.type==='biker')shoot(e.x,e.y,e.dir,false,12,280);else if(Math.abs(e.x-player.x)<80&&Math.abs(e.y-player.y)<36)damagePlayer(e.type==='brute'?20:13,e.x);e.state='walk';e.timer=rand(1.3,2.5);}}return;}if(e.state==='charge'){e.x+=e.vx*dt;e.y=approach(e.y,e.targetY,160*dt);if(Math.abs(e.x-player.x)<92&&Math.abs(e.y-player.y)<45)damagePlayer(25,e.x-e.dir*50);if(e.timer<=0){e.state='walk';e.timer=1.3;}return;}
 e.dir=Math.sign(player.x-e.x)||e.dir;const distance=Math.abs(player.x-e.x),dy=Math.abs(player.y-e.y);let speed=e.boss?(e.phase===2?96:65):e.type==='brute'?62:e.type==='raptor'?125:95;speed*=difficulty==='arcade'?1.15:1;
 const range=e.type==='gunner'||e.type==='biker'?270:e.boss?110:57;if(distance>range-8)e.x+=e.dir*speed*dt;if(dy>9)e.y+=Math.sign(player.y-e.y)*speed*.52*dt;
 if(e.type==='gunner'&&distance<130)e.x-=e.dir*speed*.45*dt;
 if(e.timer<=0&&distance<range+20&&dy<(e.boss?150:35)){if(e.boss)bossMove(e);else{e.state='windup';e.timer=.45;}}
 for(const other of enemies)if(other!==e&&!other.dead&&Math.abs(other.x-e.x)<30&&Math.abs(other.y-e.y)<28){e.y+=Math.sign(e.y-other.y||e.id-other.id)*23*dt;}
 if(lock)e.x=clamp(e.x,lock.left+20,lock.right-35);e.y=clamp(e.y,GROUND+25,FLOOR-15);
}
function gamepad(){const pads=navigator.getGamepads?.()||[];const p=Array.from(pads).find(Boolean);if(!p){padKeys.clear();return;}const map=['KeyK','KeyE','KeyJ','KeyL'];for(let i=0;i<4;i++){if(p.buttons[i]?.pressed){if(!padKeys.has(map[i]))pressed.add(map[i]);padKeys.add(map[i]);}else padKeys.delete(map[i]);}for(const [key,on] of [['ArrowLeft',p.axes[0]<-.3||p.buttons[14]?.pressed],['ArrowRight',p.axes[0]>.3||p.buttons[15]?.pressed],['ArrowUp',p.axes[1]<-.3||p.buttons[12]?.pressed],['ArrowDown',p.axes[1]>.3||p.buttons[13]?.pressed]]){if(on)padKeys.add(key);else padKeys.delete(key);}if(p.buttons[9]?.pressed&&!gamepad.pauseHeld)pause();gamepad.pauseHeld=p.buttons[9]?.pressed;}
const down=(...ks)=>ks.some(k=>keys.has(k)||padKeys.has(k)),tap=(...ks)=>ks.some(k=>pressed.has(k));
function update(dt){time+=dt;music(dt);if(state!=='play'){pressed.clear();return;}gamepad();if(state!=='play')return;if(hitstop>0){hitstop-=dt;return;}stageTimer+=dt;runTime+=dt;const h=HEROES[selected];player.anim+=dt;player.inv=Math.max(0,player.inv-dt);player.hurt=Math.max(0,player.hurt-dt);player.attack=Math.max(0,player.attack-dt);player.special=Math.max(0,player.special-dt);player.specialCd=Math.max(0,player.specialCd-dt);player.boost=Math.max(0,player.boost-dt);player.boostCd=Math.max(0,player.boostCd-dt);
 let dx=(down('ArrowRight','KeyD')?1:0)-(down('ArrowLeft','KeyA')?1:0),dy=(down('ArrowDown','KeyS')?1:0)-(down('ArrowUp','KeyW')?1:0);player.run=down('ShiftLeft','ShiftRight');player.move=!!(dx||dy);if(dx)player.dir=dx;
 if(player.hurt<=0&&player.special<=0){const speed=level.drive?185:h.speed*(player.run?1.65:1);const drag=player.attack>0?.25:1;player.x+=(dx*speed*drag+(level.drive?100*(player.boost>0?2:1):0))*dt;player.y+=dy*speed*.68*dt;if(dx&&dy){player.x-=dx*speed*drag*dt*.25;player.y-=dy*speed*.68*dt*.25;}}
 player.x=clamp(player.x,lock?lock.left+30:camera+25,lock?lock.right-70:level.length+130);player.y=clamp(player.y,GROUND+30,FLOOR-14);
 if(player.z>0){player.vz-=850*dt;player.z+=player.vz*dt;if(player.z<=0){player.z=0;player.vz=0;burst(player.x,player.y,'#8b9470',4);}}
 if(down('KeyJ','KeyZ','Space'))attack();if(tap('KeyK','KeyX'))jump();if(tap('KeyL','KeyC'))special();if(tap('KeyE','KeyV'))pickup();
 for(const d of [...drops]){d.life-=dt;if(d.type==='food'&&Math.hypot(d.x-player.x,d.y-player.y)<30){player.hp=Math.min(player.maxhp,player.hp+45);popup(player.x,player.y-90,'+45 HEALTH','#d5ec69');drops.splice(drops.indexOf(d),1);sfx('pickup');}else if(d.life<=0)drops.splice(drops.indexOf(d),1);}
 for(const e of enemies)updateEnemy(e,dt);enemies=enemies.filter(e=>!e.remove);
 for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.friendly){for(const e of enemies)if(!e.dead&&Math.abs(b.x-e.x)<(e.boss?65:26)&&Math.abs(b.y-e.y)<34){damageEnemy(e,b.damage,Math.sign(b.vx)*7);b.life=0;break;}}else if(Math.abs(b.x-player.x)<(level.drive?60:22)&&Math.abs(b.y-player.y)<25){damagePlayer(b.damage,b.x-Math.sign(b.vx)*35);b.life=0;}}
 bullets=bullets.filter(b=>b.life>0);
 for(const z of zones){z.t-=dt;if(z.t<=0){burst(z.x,z.y-20,z.friendly?'#efb36d':'#c7ea91',30);shake=8;if(z.friendly){for(const e of enemies)if(Math.hypot((e.x-z.x)*.8,e.y-z.y)<z.r)damageEnemy(e,z.damage,Math.sign(e.x-z.x)*35);}else if(Math.hypot((player.x-z.x)*.8,player.y-z.y)<z.r&&(!z.air||player.z<25))damagePlayer(z.damage,z.x,!z.air);}}
 zones=zones.filter(z=>z.t>0);
 for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=320*dt;p.life-=dt;}particles=particles.filter(p=>p.life>0);for(const f of floating){f.y-=30*dt;f.life-=dt;}floating=floating.filter(f=>f.life>0);
 if(comboTimer>0){comboTimer-=dt;if(comboTimer<=0)combo=0;}toastTime=Math.max(0,toastTime-dt);shake=Math.max(0,shake-dt*22);flash=Math.max(0,flash-dt);
 const alive=enemies.filter(e=>!e.dead);if(lock&&alive.length===0&&enemies.length===0){lock=null;toast=bossSpawned?'PATH TO EDEN IS CLEAR':'GO →';toastTime=2.5;if(bossSpawned){stageClear();return;}drops.push({x:player.x+100,y:player.y,type:wave%2?'food':'bomb',life:60});score+=500;}
 if(!lock&&!bossSpawned&&wave<4&&player.x>350+wave*520)spawnWave(wave+1);if(!lock&&wave>=4&&!bossSpawned&&player.x>level.length-400)spawnBoss();
 const target=clamp(player.x-255,0,level.length-W+180);camera=approach(camera,target,500*dt);pressed.clear();
}
function rect(g,x,y,w,h,c){g.fillStyle=c;g.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h));}
function poly(g,pts,c){g.fillStyle=c;g.beginPath();pts.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.closePath();g.fill();}
function noise(n){return Math.abs(Math.sin(n*127.1+311.7)*43758.5453)%1;}
function tree(g,x,y,s=1,theme='jungle'){g.save();g.translate(Math.round(x),y);g.scale(s,s);rect(g,-9,-138,19,145,'#26382e');rect(g,1,-127,7,132,'#48543a');poly(g,[[-3,-130],[-36,-183],[-20,-188],[10,-125]],'#344537');const colors=theme==='harbor'?['#315e42','#497c4b','#6c8e53']:['#274a35','#3b6140','#577444','#6f8a50'];for(let k=0;k<30;k++){const xx=(noise(k+x)-.5)*135,yy=-130-noise(k*8+x)*70;rect(g,xx,yy,24+noise(k+4)*25,10+noise(k+7)*18,colors[k%4]);}for(let k=0;k<6;k++)rect(g,-3+k*2,-185+k*12,3,11,'#6c8447');g.restore();}
function building(g,x,y,w,h,seed=1){rect(g,x,y-h,w,h,'#334a48');rect(g,x+5,y-h+3,w-9,h-3,'#425b54');rect(g,x+w-15,y-h+3,14,h,'#2c403d');for(let yy=y-h+12;yy<y-8;yy+=17)for(let xx=x+9;xx<x+w-18;xx+=17){rect(g,xx,yy,8,11,noise(xx+yy+seed)>.7?'#8e9d71':'#243e3d');rect(g,xx,yy,8,2,'#607c69');}for(let j=0;j<7;j++){const xx=x+noise(j+seed)*w;rect(g,xx,y-h+noise(j+8)*h,4,30,'#607847');}poly(g,[[x,y-h],[x+12,y-h-8],[x+w-9,y-h-8],[x+w,y-h]],'#62766a');}
function background(g,idx,cam,t){const l=LEVELS[idx],grad=g.createLinearGradient(0,0,0,270);grad.addColorStop(0,l.sky[0]);grad.addColorStop(1,l.sky[1]);g.fillStyle=grad;g.fillRect(0,0,W,H);if(l.theme==='harbor'||l.theme==='highway'){g.fillStyle='#e7c18a';g.beginPath();g.arc(585-cam*.025,92,35,0,Math.PI*2);g.fill();for(let j=0;j<4;j++)rect(g,0,65+j*13,W,3,l.sky[0]+'35');}
 if(l.theme==='harbor'||l.theme==='highway'||l.theme==='foundry'){for(let j=-1;j<12;j++){const x=j*94-((cam*.18)%94),h=50+noise(j+15)*125;building(g,x,225,65+noise(j)*34,h,j+8);}}
 if(l.theme==='harbor'){rect(g,0,207,W,47,'#677f6c');for(let j=0;j<14;j++)rect(g,(j*77+Math.sin(t+j)*8-cam*.1)%W,210+j%5*7,55,2,j%2?'#a9ad82':'#3c655a');for(let j=0;j<4;j++){const x=j*300-((cam*.5)%300);rect(g,x+22,127,8,118,'#283f3d');poly(g,[[x+22,134],[x+135,116],[x+148,123],[x+30,143]],'#2e4640');rect(g,x+132,120,2,61,'#394d45');}poly(g,[[0,244],[W,244],[W,281],[0,281]],'#4b6850');}
 if(l.theme==='jungle'||l.theme==='highway'||l.theme==='eden'){for(let j=-1;j<8;j++)tree(g,j*140-((cam*.27)%140),277,.95,l.theme);for(let j=-1;j<6;j++)tree(g,j*220-((cam*.55)%220),286,1.3,l.theme);}
 if(l.theme==='highway'){rect(g,0,217,W,13,'#526553');rect(g,0,228,W,6,'#abb58b');for(let j=-1;j<6;j++)rect(g,j*190-((cam*.6)%190),230,15,59,'#53604b');}
 if(l.theme==='foundry'){for(let j=-1;j<5;j++){const x=j*235-((cam*.45)%235);rect(g,x,74,180,180,'#373e38');rect(g,x+12,88,156,150,'#464b40');rect(g,x+48,26,34,110,'#3e4840');rect(g,x+53,26,6,92,'#69705a');for(let k=0;k<5;k++){rect(g,x+22+k*27,138,17,48,'#d48b4d');rect(g,x+25+k*27,140,10,41,'#f3b362');}rect(g,x+14,207,150,30,'#303b34');for(let k=0;k<7;k++)rect(g,x+16+k*23,207,12,4,'#b78c52');for(let k=0;k<5;k++)rect(g,x+55+Math.sin(t*.6+k)*13,12-k*16,35+k*8,12,'#73816a55');}}
 if(l.theme==='lab'||l.theme==='eden'){rect(g,0,0,W,255,l.theme==='lab'?'#1a333a':'#193a2e');for(let j=-1;j<5;j++){const x=j*245-((cam*.55)%245);rect(g,x,18,225,241,'#31534b');rect(g,x+8,27,209,220,'#233e3b');rect(g,x+13,34,197,3,l.accent);rect(g,x+24,61,65,166,'#466d5c');rect(g,x+29,68,55,151,'#325449');for(let k=0;k<7;k++)rect(g,x+33,80+k*18,47,2,'#719377');rect(g,x+111,76,66,141,'#253f43');rect(g,x+118,82,52,127,'#4a786d');if(l.theme==='lab'){drawDino(g,x+145,187,.38,-1,'#8eb89c',true,t);rect(g,x+118,82,52,127,'#82ebcb18');}else{for(let k=0;k<14;k++)rect(g,x+119+noise(k)*43,92+noise(k+2)*111,7,8,['#a5b868','#a58954','#6f9958'][k%3]);}rect(g,x+98,232,95,7,'#789e82');}if(l.theme==='eden'){for(let j=-1;j<5;j++)tree(g,j*260-((cam*.65)%260),290,.9);}}
 const ground=g.createLinearGradient(0,GROUND,0,H);ground.addColorStop(0,l.road[0]);ground.addColorStop(1,l.road[1]);g.fillStyle=ground;g.fillRect(0,GROUND,W,H-GROUND);rect(g,0,GROUND,W,8,'#8f9a6b');rect(g,0,GROUND+8,W,3,'#233c2d');
 if(l.drive){rect(g,0,GROUND+15,W,147,'#454b40');for(let lane=0;lane<3;lane++)for(let j=-1;j<9;j++)rect(g,j*115-((cam+t*95)%115),300+lane*43,54,3,'#b3b083');rect(g,0,414,W,3,'#8c966b');}
 else{for(let j=0;j<12;j++){const y=281+j*15;rect(g,0,y,W,1,'#243c324a');for(let k=-1;k<9;k++){const x=k*120+(j%2)*60-(cam%120);rect(g,x,y,1,15,'#a8af7920');}}for(let j=0;j<130;j++){const x=((noise(j+9)*W-cam*.85)%W+W)%W,y=275+noise(j+41)*150;rect(g,x,y,2+noise(j)*6,1,noise(j+1)>.5?'#9da76d45':'#16362666');}}
 if(l.theme==='harbor'){for(let j=-1;j<4;j++){const x=j*530-(cam%530);rect(g,x+340,245,9,28,'#2c4136');rect(g,x+380,245,9,28,'#2c4136');rect(g,x+335,241,59,7,'#6c7950');rect(g,x+347,250,31,3,'#9f9d65');}}
 if(l.theme==='foundry'){for(let j=-1;j<5;j++){const x=j*380-(cam%380);rect(g,x+50,262,90,15,'#a67e45');for(let k=0;k<9;k++)poly(g,[[x+50+k*10,262],[x+55+k*10,262],[x+65+k*10,277],[x+60+k*10,277]],'#323f35');}}
 for(let j=0;j<5;j++){const x=((j*237-cam*.72)%920+920)%920-60;const yy=241;poly(g,[[x,yy],[x+5,yy-18],[x+8,yy],[x+14,yy-12],[x+15,yy]],'#7a9254');}
}
function drawFrame(g,f,x,y,scale=1.35,dir=1,filter='none'){if(!f||!sheet.complete)return;g.save();g.imageSmoothingEnabled=false;g.translate(Math.round(x),Math.round(y));g.scale(-dir*scale,scale);g.filter=filter;g.drawImage(sheet,f.x,f.y,f.w,f.h,-f.anchor,-f.h,f.w,f.h);g.restore();}
function shadow(g,x,y,w=25){g.fillStyle='#10271b66';g.beginPath();g.ellipse(x,y,w,6,0,0,Math.PI*2);g.fill();}
function drawDino(g,x,y,s,dir,color='#849955',mutant=false,t=0){g.save();g.translate(Math.round(x),Math.round(y));g.scale(dir*s,s);const leg=Math.sin(t*10)*7;poly(g,[[-77,-30],[-127,-18],[-112,-10],[-51,-13],[-13,8],[31,-4],[36,-53],[73,-77],[90,-104],[45,-112],[29,-104],[15,-86],[-6,-65],[-38,-55]],'#20382d');poly(g,[[-74,-29],[-119,-17],[-49,-24],[-17,0],[25,-6],[28,-56],[71,-83],[83,-101],[45,-106],[32,-98],[19,-78],[-9,-61],[-37,-50]],color);poly(g,[[-39,-48],[-20,-57],[11,-57],[22,-39],[11,-12],[-16,-6]],mutant?'#c6d1af':'#adba75');poly(g,[[17,-65],[38,-69],[42,-59],[26,-53],[25,-34],[15,-37]],'#cad391');poly(g,[[42,-97],[78,-99],[88,-91],[43,-83]],'#2c4132');for(let j=0;j<5;j++)poly(g,[[47+j*7,-96],[50+j*7,-88],[53+j*7,-96]],'#e6e7c7');rect(g,54,-105,8,5,mutant?'#ef9360':'#ecdb77');rect(g,56,-105,3,5,'#162f23');poly(g,[[-6,-9],[-12+leg,12],[-31+leg,24],[-4+leg,24],[14,-1]],'#4d633a');poly(g,[[15,-2],[27-leg,15],[8-leg,24],[37-leg,24],[37,-9]],color);rect(g,-31+leg,21,29,4,'#ddd8ad');rect(g,8-leg,21,29,4,'#ddd8ad');if(mutant){for(let j=0;j<5;j++)poly(g,[[-39+j*15,-49+j*2],[-32+j*15,-70+j*2],[-23+j*15,-50+j*2]],'#d3dfb9');for(let j=0;j<3;j++)rect(g,-30+j*12,-32,5,8,'#90d88b');}g.restore();}
function drawRegent(g,e,x,y){g.save();g.translate(x,y);g.scale(e.dir,1);shadow(g,0,2,70);const bob=Math.sin(e.anim*3)*2;g.translate(0,bob);poly(g,[[-82,-40],[-150,-14],[-150,-5],[-64,-14],[-17,5],[52,-6],[59,-84],[90,-123],[108,-139],[105,-161],[48,-171],[28,-155],[14,-114],[-28,-101],[-66,-83]],'#233b35');poly(g,[[-80,-38],[-143,-11],[-56,-27],[-16,-1],[47,-9],[49,-86],[85,-128],[103,-142],[100,-157],[49,-165],[34,-147],[23,-104],[-29,-95],[-62,-78]],'#cbd2b5');poly(g,[[-55,-76],[-29,-92],[14,-97],[36,-75],[34,-33],[-12,-9],[-38,-28]],'#94a991');for(let k=0;k<6;k++)poly(g,[[-62+k*15,-81-k*4],[-59+k*15,-103-k*4],[-47+k*15,-84-k*4]],'#e9ebce');poly(g,[[43,-145],[101,-147],[112,-136],[47,-126]],'#263b36');for(let j=0;j<6;j++)poly(g,[[49+j*9,-146],[52+j*9,-132],[56+j*9,-146]],'#f3efd8');rect(g,67,-157,12,5,'#f6ab64');rect(g,71,-158,3,7,'#b7473c');poly(g,[[22,-100],[57,-104],[62,-95],[38,-87],[34,-52],[22,-57]],'#bbc9a7');poly(g,[[-14,-9],[-31,15],[-60,26],[-24,26],[8,-5]],'#98ab8a');poly(g,[[29,-8],[49,12],[23,25],[66,25],[58,-20]],'#d5dbc1');rect(g,-59,22,36,5,'#f0e8cc');rect(g,25,21,43,5,'#f0e8cc');rect(g,-33,-68,38,26,'#365e4d');rect(g,-28,-64,29,17,'#b7e280');rect(g,-22,-62,5,13,'#e5f2aa');for(let j=0;j<4;j++)rect(g,-39,-22-j*10,19,3,'#728e78');g.restore();}
function car(g,x,y,scale=1,boost=false,t=0){g.save();g.translate(x,y);g.scale(scale,scale);shadow(g,0,4,72);poly(g,[[-77,-31],[-57,-53],[-27,-59],[26,-57],[45,-39],[78,-34],[87,-11],[75,-3],[-73,-3],[-86,-11]],'#1b3029');poly(g,[[-78,-29],[-51,-46],[39,-42],[77,-30],[82,-13],[-79,-13]],'#78ac79');poly(g,[[-39,-53],[-24,-57],[23,-55],[35,-43],[-48,-44]],'#d7d1a0');poly(g,[[-37,-52],[-24,-54],[-5,-54],[-5,-43],[-46,-44]],'#315653');poly(g,[[0,-54],[23,-52],[32,-43],[0,-43]],'#315653');rect(g,-75,-26,150,5,'#a8c394');rect(g,-64,-13,127,5,'#496e51');rect(g,69,-25,13,8,'#fff1bd');rect(g,-81,-23,7,8,'#d4945e');rect(g,-86,-11,171,4,'#ddd7ae');for(const xx of [-48,50]){g.fillStyle='#17231e';g.beginPath();g.arc(xx,-3,16,0,Math.PI*2);g.fill();g.fillStyle='#829a83';g.beginPath();g.arc(xx,-3,9,0,Math.PI*2);g.fill();rect(g,xx-2,-9,4,12,'#c4c9a6');rect(g,xx-6,-5,12,4,'#c4c9a6');}rect(g,3,-27,13,3,'#d4daba');rect(g,22,-22,15,2,'#314e3d');if(boost){poly(g,[[-85,-17],[-124-Math.sin(t*20)*18,-4],[-105,-20],[-137,-27],[-84,-23]],'#eaaa56');poly(g,[[-85,-17],[-117,-11],[-104,-23],[-84,-21]],'#e9df91');}g.restore();}
function truck(g,e,x,y){g.save();g.translate(x,y);shadow(g,0,5,110);rect(g,-92,-96,123,79,'#46564b');rect(g,-89,-91,118,11,'#728069');rect(g,-84,-74,105,47,'#2c4037');for(let j=0;j<5;j++)rect(g,-80+j*21,-69,3,40,'#687958');poly(g,[[25,-68],[66,-68],[94,-47],[106,-25],[100,-8],[23,-8]],'#7d8662');rect(g,34,-62,31,23,'#263e38');rect(g,73,-40,23,11,'#c6c59a');rect(g,26,-25,73,8,'#425b44');rect(g,-97,-13,202,7,'#bbc29c');for(const xx of [-62,64]){g.fillStyle='#192f25';g.beginPath();g.arc(xx,-7,22,0,Math.PI*2);g.fill();g.fillStyle='#91a27b';g.beginPath();g.arc(xx,-7,11,0,Math.PI*2);g.fill();}rect(g,-25,-113,43,13,'#596c54');rect(g,-57,-109,36,7,'#a8b28a');g.restore();}
function drawFighter(e){const x=e.x-camera,y=e.y-e.z,dying=e.dead>0;ctx.save();if(dying)ctx.globalAlpha=clamp(e.dead/.8,0,1);if(e.inv>0&&Math.floor(time*18)%2===0&&!e.boss)ctx.globalAlpha=.6;shadow(ctx,x,e.y,e.boss?45:25);if(e.boss&&e.type==='regent'&&e.phase===2){drawRegent(ctx,e,x,y);}
 else if(e.type==='raptor'){drawDino(ctx,x,y, e.boss?1.3:.72,e.dir,e.boss?'#abbd7b':'#718e52',true,e.anim);}
 else if(e.type==='truck'){truck(ctx,e,x,y);}
 else{const pal=e.type==='regent'?'14':e.palette;const frames=A.enemies[pal];let idx=pal==='14'?(e.hurt>0?11:e.state==='windup'?9:[2,3,4,5][Math.floor(e.anim*7)%4]):[1,2,3,4,5,6][Math.floor(e.anim*7)%6];if(!frames[idx])idx=0;const filter=e.type==='regent'?'grayscale(1) brightness(1.5)':e.type==='echo'?'hue-rotate(140deg) brightness(1.15)':e.type==='cinder'?'hue-rotate(320deg)':e.hue?`hue-rotate(${e.hue}deg)`:'none';drawFrame(ctx,frames[idx],x,y,e.boss?1.75:e.type==='brute'?1.55:1.25,e.dir,filter);
 if(level.drive&&e.type==='biker'){rect(ctx,x-32,y-20,65,10,'#a79655');for(const xx of [-22,22]){ctx.fillStyle='#142f24';ctx.beginPath();ctx.arc(x+xx,y-3,13,0,Math.PI*2);ctx.fill();rect(ctx,x+xx-3,y-8,6,10,'#809278');}}
 if(e.type==='warden'){rect(ctx,x-20,y-80,34,21,'#859078');rect(ctx,x-17,y-76,28,4,'#c0c5a1');rect(ctx,x+e.dir*35-8,y-65,12,48,'#87957c');rect(ctx,x+e.dir*35-13,y-52,22,6,'#cccd9e');}}
 if(e.state==='windup'){ctx.fillStyle='#f1b16d';ctx.font='bold 22px Consolas';ctx.textAlign='center';ctx.fillText('!',x,y-(e.boss?170:112));}if(!e.boss&&e.hp<e.maxhp&&!dying){rect(ctx,x-22,e.y-110,44,4,'#172e24');rect(ctx,x-22,e.y-110,44*e.hp/e.maxhp,4,'#d5ec69');}ctx.restore();}
function drawPlayer(){const x=player.x-camera,y=player.y-player.z;ctx.save();shadow(ctx,x,player.y,level.drive?72:27);if(player.inv>0&&Math.floor(time*16)%2===0)ctx.globalAlpha=.64;if(level.drive){car(ctx,x,y,1,player.boost>0||player.special>0,time);if(player.attack>0){rect(ctx,x+85,y-40,24,7,'#f2dc8c');}}else{const data=A[HEROES[selected].id];let anim=player.special>0?'special':player.hurt>0?'hurt':player.z>0?'jump':player.attack>0?'attack':player.move?'walk':'idle';const list=data[anim];const frame=player.attack>0&&anim==='attack'?Math.floor((1-player.attack/player.attackTotal)*list.length):player.special>0?Math.floor((.65-player.special)*18):Math.floor(player.anim*(anim==='walk'?player.run?16:10:anim==='idle'?3:6));drawFrame(ctx,data.frames[list[frame%list.length]],x,y,1.35,player.dir);
 if(player.weapon==='gun'){ctx.save();ctx.translate(x+player.dir*25,y-57);ctx.scale(player.dir,1);rect(ctx,0,-3,27,7,'#2b3f36');rect(ctx,6,4,5,9,'#648474');rect(ctx,25,-2,9,3,'#b5c1a2');ctx.restore();}if(player.weapon==='knife'){rect(ctx,x+player.dir*28,y-52,14,3,'#e3e4c4');}}
 if(player.special>0){ctx.strokeStyle=HEROES[selected].color;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(x,y-40,90*(1-player.special/.9),35,0,0,Math.PI*2);ctx.stroke();}ctx.restore();}
function drawObject(o){if(o.hp<=0)return;const x=o.x-camera;shadow(ctx,x,o.y,23);if(o.type==='barrel'){drawFrame(ctx,A.enemies['5'][0],x,o.y,1,1);}else{rect(ctx,x-23,o.y-46,46,46,'#3b4c33');rect(ctx,x-21,o.y-44,42,40,'#9b7b4c');for(let j=0;j<3;j++)rect(ctx,x-18+j*13,o.y-42,2,38,'#5e603e');rect(ctx,x-23,o.y-43,46,6,'#bf9959');rect(ctx,x-23,o.y-9,46,6,'#bf9959');}}
function drawDrop(d){const x=d.x-camera,y=d.y+Math.sin(time*4+d.x)*3;shadow(ctx,x,d.y,14);if(d.type==='food'){rect(ctx,x-12,y-13,24,10,'#d7bb73');rect(ctx,x-10,y-18,19,6,'#b25e42');rect(ctx,x-9,y-21,16,3,'#d28d55');rect(ctx,x-15,y-4,29,3,'#e4ddb0');}else if(d.type==='gun'){rect(ctx,x-18,y-17,32,7,'#a9bcb0');rect(ctx,x-12,y-10,6,12,'#5e7b66');rect(ctx,x+11,y-15,12,4,'#dce0bd');}else if(d.type==='knife'){rect(ctx,x-18,y-13,22,4,'#d5dbc1');poly(ctx,[[x+4,y-13],[x+18,y-11],[x+4,y-9]],'#d5dbc1');rect(ctx,x-20,y-14,9,6,'#906d48');}else{ctx.fillStyle='#9eac74';ctx.beginPath();ctx.arc(x,y-10,10,0,Math.PI*2);ctx.fill();rect(ctx,x-2,y-25,4,8,'#e8bc70');}if(Math.hypot(d.x-player.x,d.y-player.y)<65&&d.type!=='food'){label('E · '+d.type.toUpperCase(),x,y-34,10,'#d5ec69','center');}}
function label(text,x,y,size=12,color='#ecebcf',align='left'){ctx.font=`bold ${size}px Consolas, monospace`;ctx.textAlign=align;ctx.fillStyle='#12261e';ctx.fillText(text,x+1,y+1);ctx.fillStyle=color;ctx.fillText(text,x,y);}
function hud(){rect(ctx,0,0,W,68,'#0c1d19dc');rect(ctx,0,67,W,1,'#678258');const h=HEROES[selected];const fr=A[h.id].frames[0];ctx.save();ctx.beginPath();ctx.rect(16,12,42,45);ctx.clip();drawFrame(ctx,fr,38,117,1.25,1);ctx.restore();rect(ctx,16,12,42,2,h.color);label(h.name,70,23,12,h.color);rect(ctx,70,31,182,10,'#374a35');rect(ctx,71,32,180*clamp(player.hp/player.maxhp,0,1),8,h.color);label(`${Math.ceil(player.hp)} / ${Math.ceil(player.maxhp)}   × ${lives}`,70,56,10,'#c1cba6');label(level.area,285,23,10,'#b0c19f');label(level.name,285,43,13,'#e6e7c8');label('SCORE '+score.toString().padStart(7,'0'),W-53,23,12,'#e1e6ba','right');label(level.drive?'CADILLAC · GUN ∞':player.weapon?player.weapon.toUpperCase()+' · '+player.ammo:'BARE HANDS',W-53,43,10,'#adc197','right');
 const b=enemies.find(e=>e.boss&&!e.dead);if(b){rect(ctx,193,H-41,382,24,'#0e231bdd');rect(ctx,203,H-30,362,7,'#384a35');rect(ctx,204,H-29,360*Math.max(0,b.hp/b.maxhp),5,b.phase===2?'#d5ec69':'#e9a56b');label(b.type==='regent'&&b.phase===2?'THE PALE REGENT':level.boss,W/2,H-35,10,'#efdfb8','center');}
 else{rect(ctx,18,H-19,130,3,'#2c4534');rect(ctx,18,H-19,130*clamp(player.x/level.length,0,1),3,'#9aad6b');label('CHAPTER 0'+(levelIndex+1),18,H-25,9,'#b8c59d');}
 if(combo>=2){label(combo+' HIT',W-22,102,27,'#d5ec69','right');label('COMBO',W-25,116,10,'#b7c69c','right');}
 if(toastTime>0){rect(ctx,W/2-250,78,500,25,'#153023dc');label(toast,W/2,95,11,'#e0e8a8','center');}
 if(player.specialCd>0){label('SPECIAL '+Math.ceil(player.specialCd)+'s',18,94,10,'#a6b797');}else label(level.drive?'L · RAM READY':'L · '+h.special.toUpperCase(),18,94,9,'#d5ec69');}
function render(){ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,W,H);ctx.save();if(shake>0)ctx.translate(rand(-shake,shake),rand(-shake/2,shake/2));
 if(!started||['menu','select','chapters','credits'].includes(state)){background(ctx,0,time*9,time);rect(ctx,0,0,W,H,'#0a221ec0');car(ctx,125,415,1.1,false,time);HEROES.forEach((h,i)=>{drawFrame(ctx,A[h.id].frames[0],340+i*90,424,1.1,1);});rect(ctx,0,0,W,H,'#05131030');}
 else{background(ctx,levelIndex,camera,time);for(const z of zones){const x=z.x-camera;ctx.fillStyle=z.friendly?'#efb36638':'#e77d5a30';ctx.beginPath();ctx.ellipse(x,z.y,z.r,z.r*.4,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=z.friendly?'#e8bd76':'#efa36b';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,z.y,z.r*(z.t/z.total),z.r*.4*(z.t/z.total),0,0,Math.PI*2);ctx.stroke();}
 const draws=[...objects.filter(o=>o.hp>0).map(o=>({y:o.y,fn:()=>drawObject(o)})),...drops.map(d=>({y:d.y,fn:()=>drawDrop(d)})),...enemies.map(e=>({y:e.y,fn:()=>drawFighter(e)})),{y:player.y,fn:drawPlayer}];draws.sort((a,b)=>a.y-b.y);draws.forEach(d=>d.fn());for(const b of bullets){rect(ctx,b.x-camera,b.y-b.z,Math.sign(b.vx)*17,3,b.color);rect(ctx,b.x-camera,b.y-b.z-1,4,5,'#fff3bb');}for(const p of particles)rect(ctx,p.x-camera,p.y,p.size,p.size,p.color);for(const f of floating)label(f.text,f.x-camera,f.y,12,f.color,'center');hud();
 if(lock&&!bossSpawned){label('CLEAR THE AREA',W/2,123,9,'#d4cf9e','center');}else if(!bossSpawned&&toastTime<=0){label('GO →',W-38,220,19,'#d5ec69','right');}if(state!=='play')rect(ctx,0,0,W,H,'#0b1a1688');}
 if(flash>0)rect(ctx,0,0,W,H,`rgba(226,239,170,${Math.min(.5,flash)})`);ctx.restore();}
function frame(now){const dt=Math.min(.033,(now-last)/1000||.016);last=now;update(dt);render();requestAnimationFrame(frame);}
window.addEventListener('keydown',e=>{const use=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD','KeyJ','KeyK','KeyL','KeyZ','KeyX','KeyC','KeyE','KeyV','ShiftLeft','ShiftRight','Enter','Escape','KeyP'];if(use.includes(e.code)&&(state==='play'||['ArrowLeft','ArrowRight','Enter','Escape','KeyP'].includes(e.code)))e.preventDefault();unlockAudio();if(e.code==='Escape'||e.code==='KeyP'){if(!e.repeat){if(state==='play'||state==='paused')pause();else if(e.code==='Escape'&&['select','chapters','guide','credits'].includes(state))menu();}return;}if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code);if(e.code==='Enter'&&!e.repeat){if(state==='menu')characterSelect();else if(state==='select')document.getElementById('begin')?.click();else if(state==='brief')document.getElementById('enter-stage')?.click();else if(state==='clear')document.getElementById('next')?.click();else if(state==='gameover')document.getElementById('retry')?.click();}if(state==='select'&&!e.repeat&&['ArrowLeft','ArrowRight'].includes(e.code)){selected=(selected+(e.code==='ArrowRight'?1:3))%4;characterSelect();}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();pressed.clear();if(state==='play')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='play')pause();});
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;const release=()=>{keys.delete(k);touchKeys.delete(k);};b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);unlockAudio();if(!keys.has(k))pressed.add(k);keys.add(k);touchKeys.add(k);});b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);});
bindButton('pause',pause);bindButton('home',()=>{if(state==='play')pause();else menu();});bindButton('sound',()=>{const on=settings.music||settings.sfx;settings.music=!on;settings.sfx=!on;document.querySelector('#sound').textContent=on?'SOUND OFF':'SOUND ON';persist();});document.querySelector('#sound').textContent=settings.music||settings.sfx?'SOUND ON':'SOUND OFF';bindButton('full',()=>{if(document.fullscreenElement)document.exitFullscreen();else document.querySelector('.game-shell').requestFullscreen?.().catch(()=>{});});
// A narrow, explicit test interface keeps campaign checks reproducible.
window.LAST_EDEN={get state(){return state;},get snapshot(){return {state,level:levelIndex,wave,score,lives,player:player?{...player}:null,enemies:enemies.map(e=>({...e})),objects:objects.map(o=>({...o})),drops:drops.map(d=>({...d})),unlocked:save.unlocked};},start:(i=0,hero=0,mode='story')=>{selected=clamp(hero,0,3);difficulty=mode;score=0;lives=3;startStage(clamp(i,0,5),true);},step:(dt=1/60)=>update(dt),controls:{attack,jump,special,pickup},test:{move:(x,y)=>{player.x=x;player.y=y;},damageEnemy:(i,n)=>damageEnemy(enemies[i],n),damagePlayer:n=>damagePlayer(n,player.x-40),finishEncounter:()=>{enemies.forEach(e=>{e.inv=0;damageEnemy(e,9999);if(e.phase===2&&e.hp>0){e.inv=0;damageEnemy(e,9999);}});},spawnBoss,clear:stageClear}};
sheet.onload=()=>{if(state==='select')characterSelect();};sheet.onerror=()=>panel('<section class="panel small-panel"><h2>ARTWORK COULD NOT LOAD.</h2><p>Keep assets.js, game.js and index.html in the same folder, then open index.html again.</p></section>');menu();requestAnimationFrame(frame);
})();
